[workspace]
resolver = "3"
members = [
    "crates/crystalskk-art",
    "crates/crystalskk-core",
    "crates/crystalskk-dict",
    "crates/crystalskk-ipc",
    "crates/crystalskk-lm",
    "crates/crystalskk-settings",
    "crates/crystalskk-server",
    "crates/crystalskk-fetch",
    "crates/crystalskk-cli",
    "crates/crystalskk-tip",
    "crates/crystalskk-setup",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
rust-version = "1.93"
repository = "https://github.com/hisaknown/CrystalSKK"

[workspace.lints.rust]
missing_debug_implementations = "warn"
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
